### ISSUE TITLE
Game ran out of memory

### ISSUE THREAD

**Issue by Zendelll** [MountainDrew8/Something#29]
Server crushing on bosses after 1-2 minutes of boss. Tested on king slime and eye of cthulhu

Logs:\
[22:24:00] [Server Hang Watchdog/ERROR] [tML]: Server hung for more than 10 seconds:
   в System.Windows.Forms.SafeNativeMethods.MessageBox(HandleRef hWnd, String text, String caption, Int32 type)
   в System.Windows.Forms.MessageBox.ShowCore(IWin32Window owner, String text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean showHelp)
   в Terraria.ModLoader.UI.Interface.MessageBoxShow(String text, String caption)
   в Terraria.ModLoader.Logging.FirstChanceExceptionHandler(Object sender, FirstChanceExceptionEventArgs args)
   в System.Collections.Generic.Dictionary`2.Initialize(Int32 capacity)
   в System.Collections.Generic.Dictionary`2..ctor(Int32 capacity, IEqualityComparer`1 comparer)
   в CalamityMod.CalPlayer.CalamityPlayer.HandleCooldownDictionary(BinaryReader reader) в CalamityMod\CalPlayer\CalamityPlayerNetcode.cs:строка 325
   в CalamityMod.CalamityNetcode.HandlePacket(Mod mod, BinaryReader reader, Int32 whoAmI) в CalamityMod\CalamityNetcode.cs:строка 84
   в CalamityMod.CalamityMod.HandlePacket(BinaryReader reader, Int32 whoAmI) в CalamityMod.cs:строка 1619
   в Terraria.ModLoader.ModNet.HandleModPacket(BinaryReader reader, Int32 whoAmI, Int32 length)
   в DMD<Terraria.MessageBuffer::GetData>(MessageBuffer this, Int32 start, Int32 length, Int32& messageType)
   в Trampoline<Terraria.MessageBuffer::GetData>?12562992(MessageBuffer , Int32 , Int32 , Int32& )
   в MagicStorage.Edits.Detours.Vanilla.MessageBuffer_GetData(orig_GetData orig, MessageBuffer self, Int32 start, Int32 length, Int32& messageType) в MagicStorage\Edits\Detours\Vanilla.NetMessage.cs:строка 164
   в Hook<Terraria.MessageBuffer::GetData>?1635619(MessageBuffer , Int32 , Int32 , Int32& )
   в Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
   в Terraria.Netplay.<>c.<ServerLoop>b__46_2()
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()
   в System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   в System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   в System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   в System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   в System.Threading.Tasks.Task.InternalRunSynchronously(TaskScheduler scheduler, Boolean waitForCompletion)
   в Terraria.Netplay.OnUpdate()
   в Terraria.Main.DoUpdate(GameTime gameTime)
   в Terraria.Main.Update(GameTime gameTime)
   в Terraria.Main.DedServ()
   в Terraria.Program.LaunchGame_()
   в Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   в Terraria.WindowsLaunch.Main(String[] args)

**Comment by Zendelll** [comment]
Ok, sorry, it was update of magic storage :)

**Comment by dude4123** [comment]
is it in multiplayer? because in multiplayer games I have that problem with a pc 16 gb of ram and tmod of 64 btis
but alone I didn't have that problem

**Comment by LubieKakao1212** [comment]
I also have this problem. @Zendelll did you managed to fix this, if so, how?

**Comment by Zendelll** [comment]
@LubieKakao1212 Sorry, I was wrong about magic storage. This memory leak exists only in multiplayer if you or you friend dies during boss fight. You can play in singleplayer or play on [v1.5.0.4](https://github.com/MountainDrew8/CalamityMod/releases/tag/v1.5.0.4). Developers said that they know about it and next patch will fix this and several other issues. If you want more info you can join [Calamity discord](https://discord.com/invite/calamity)
